{% set name = "magic_enum" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Neargye/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b403d3dad4ef542fdc3024fa37d3a6cedb4ad33c72e31b6d9bab89dcaf69edf7

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make                # [not win]
    - ninja               # [win]

test:
  commands:
    - test -f ${PREFIX}/include/magic_enum/magic_enum.hpp  # [not win]

about:
  home: https://github.com/Neargye/magic_enum
  summary: Header-only C++17 library provides static reflection for enums
  description: |
    Static reflection for enums (to string, from string, iteration) for modern C++,
    work with any enum type without any macro or boilerplate code
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Neargye/magic_enum

extra:
  recipe-maintainers:
    - versatran01
    - ManifoldFR
    - ymontmarin
